logging:
  level:
    root: INFO
    ru.yandex.practicum: INFO
    org.zalando.logbook: TRACE

spring:
  boot:
    build-info:
      package-classpath: true
  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./db/filmorate
    driverClassName: org.h2.Driver
    username: sa
    password: password
